describe("LuaForth", function()
	local luaforth = require("luaforth")
	describe("should, when given simple_env, be able to source 04-simple_env-sourcing_failing.fs and error using", function()
		it("%source", function()
			assert.has_error(function()
				luaforth.eval("%source tests/04-simple_env-sourcing_failing.fs", luaforth.simple_env)
			end)
		end)
		it("source", function()
			assert.has_error(function()
				luaforth.eval("s' tests/04-simple_env-sourcing_failing.fs' source", luaforth.simple_env)
			end)
		end)
	end)
end)
